### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by mono-nobe** [mono-nobe/sounds-album#4]
# Goal

DB設計がER図でまとめられている。
JSON、YAML、ローカルストレージその他に関しては、データ構造が実例と一緒に記載されている。

## 使用技術

- https://github.com/mono-nobe/sounds-album/issues/27
- https://github.com/mono-nobe/sounds-album/issues/28
- https://github.com/mono-nobe/sounds-album/issues/29
- https://github.com/mono-nobe/sounds-album/issues/31
- https://github.com/mono-nobe/sounds-album/issues/32

**Comment by mono-nobe** [comment]
以下にER図を記載する。

<details>
<summary>提出1回目</summary>
<img width="860" alt="image" src="https://github.com/mono-nobe/sounds-album/assets/94843475/106c3b69-30a6-43c1-bbbb-272f37b6c731">
</details>

<details>
<summary>提出2回目</summary>
<img width="911" alt="image" src="https://github.com/mono-nobe/sounds-album/assets/94843475/42f4b7f6-cb7c-4248-ba7b-6b96372b60cd">
</details>


<img width="794" alt="image" src="https://github.com/mono-nobe/sounds-album/assets/94843475/2843abfb-a20c-45ed-8a38-ff328323d5a3">

**Comment by maedana** [comment]
- 認証はDevise使うのですかね? だとするとかなり足りないカラムがあるかなーと思います。
- Rails前提でいいんですかね? だとすると各テーブルはそれぞれcreated_at, updated_atを持つことになるかなーと思います。また、主キーはそれぞれ単にidとなりますし、各種命名はスネークケースになるかなと。
- 可能なら各カラムそれぞれどんなデータ型なのか記載があるほうがわかりやすいかと思いました。
- UsersとProfilesが別れてますが、ProfilesがUserIDしか持たないなら不要なのでは? 他の項目をProfilesに追加するにしてももし数が多くないならUsersのカラムの一つとして持つだけでいいかもしれません。後々必要性が出たらUsersとProfilesに分割するのでもいいんじゃないかなと思いました。
- Soundsはこの設計でいくなら外部キーはProfileIDになるんじゃないですかね? UsersにProfilesを統合するならこのままでよさそうですが。
- SoundsのIconには何が入るイメージなんでしょう? ペーパープロトも見ましたけどよくわからなかったです。
- SettingImagesですが、URLを持つということは画像はどこか外部のサービスを使って保存する想定でしょうか? Railsでやるなら通常はActiveStroageを使うと思うのでそうなるとデータ設計変わって来そうですね。

追記
- Iconの件は `sound にアイコンとして絵文字を登録できる機能があってもいいかもですね。ディストーション系には ⚡️ を設定したり、クリーントーンには ✨ を設定したりなどができると、識別がしやすくなりそうです。` というフィードバックの対応かなと思いました。たぶんTitleの一部としてアイコンも入力出来るようになってれば済む話なのかなと思いましたー。このGithubの入力欄もまさに絵文字入れること出来ますよね。それと同じかと思いました。

**Comment by mono-nobe** [comment]
@maedana 
レビューありがとうございます！
内容を修正しましたので、ご確認をお願いします。

> 認証はDevise使うのですかね? だとするとかなり足りないカラムがあるかなーと思います。
Rails前提でいいんですかね? だとすると各テーブルはそれぞれcreated_at, updated_atを持つことになるかなーと思います。また、主キーはそれぞれ単にidとなりますし、各種命名はスネークケースになるかなと。

認証は Supabase でメールアドレスを用いる方法を想定しております！(概要に使用技術を追記しました 🙇 )
Docsを確認したところ、最低限メールアドレスとパスワードがあればよいのではないかと思い、そちらのみ記載しております。
(読み違いの可能性も十分あるため、ご指摘いただけると幸いです...)

https://supabase.com/docs/guides/auth/auth-email

> 可能なら各カラムそれぞれどんなデータ型なのか記載があるほうがわかりやすいかと思いました。

おっしゃる通りですね 👀 
こちら追記しました！

> UsersとProfilesが別れてますが、ProfilesがUserIDしか持たないなら不要なのでは? 他の項目をProfilesに追加するにしてももし数が多くないならUsersのカラムの一つとして持つだけでいいかもしれません。後々必要性が出たらUsersとProfilesに分割するのでもいいんじゃないかなと思いました。

Supabaseでのユーザー管理方法を確認すると、`users` テーブルを直接触るのではなく、 `public.profiles` のようなテーブルを作成し間接的に操作することが推奨されているようなので、今回分割する形としました！

https://supabase.com/docs/guides/auth/managing-user-data

> Soundsはこの設計でいくなら外部キーはProfileIDになるんじゃないですかね? UsersにProfilesを統合するならこのままでよさそうですが。

ありがとうございます。
ProfileIDの方が適切なので修正しました！

> SettingImagesですが、URLを持つということは画像はどこか外部のサービスを使って保存する想定でしょうか? Railsでやるなら通常はActiveStroageを使うと思うのでそうなるとデータ設計変わって来そうですね。

SupabaseのStorage機能で保存する想定です！

https://supabase.com/docs/reference/javascript/storage-from-upload

> SoundsのIconには何が入るイメージなんでしょう? ペーパープロトも見ましたけどよくわからなかったです。
たぶんTitleの一部としてアイコンも入力出来るようになってれば済む話なのかなと思いましたー。このGithubの入力欄もまさに絵文字入れること出来ますよね。それと同じかと思いました。

こちらについてはTitleの一部ではなく、Notionでのページアイコンのような形で、サウンドごとに個別のアイコンとして設定できるものをイメージしておりました！

https://shin-hack.com/notion-icon-change/

**Comment by maedana** [comment]
> 認証は Supabase でメールアドレスを用いる方法を想定しております！(概要に使用技術を追記しました 🙇 )
Docsを確認したところ、最低限メールアドレスとパスワードがあればよいのではないかと思い、そちらのみ記載しております。
(読み違いの可能性も十分あるため、ご指摘いただけると幸いです...)

Supabase使ったことがなくて全くわからないのですけど、少しドキュメント漁ってみた感じですと、`auth`スキーマ内に`users`テーブルが自動生成されるのかなと思いました。ただ、`auth`スキーマ内のデータはセキュリティのため外から自由に参照出来ないようになっているみたいですね。このUsersはつまり、Supabaseの`auth.users`のイメージなのでしょうか?

> Supabaseでのユーザー管理方法を確認すると、users テーブルを直接触るのではなく、 public.profiles のようなテーブルを作成し間接的に操作することが推奨されているようなので、今回分割する形としました！

`auth.users`が直接参照出来ないのでってことですよね。ドキュメントざっくり読んでなんとなく雰囲気はわかりました。しかし、外部キーしかないならやはり不要なんじゃないですかね? ご提示の
https://supabase.com/docs/guides/auth/managing-user-data
のような形で`Sounds`を作ればそのときに`auth.users`と紐付けられるんじゃないかなと思いましたが。

> SupabaseのStorage機能で保存する想定です！

OKです。

> こちらについてはTitleの一部ではなく、Notionでのページアイコンのような形で、サウンドごとに個別のアイコンとして設定できるものをイメージしておりました！

OKです。

**Comment by mono-nobe** [comment]
@maedana 
> このUsersはつまり、Supabaseのauth.usersのイメージなのでしょうか?

はい！いただいた通りのイメージです。

> しかし、外部キーしかないならやはり不要なんじゃないですかね? ご提示の
https://supabase.com/docs/guides/auth/managing-user-data
のような形でSoundsを作ればそのときにauth.usersと紐付けられるんじゃないかなと思いましたが。

確かに、以下のような形でsoundsテーブルを作成すればauth.usersと紐づけられそうです 👀 
(usersテーブルを参照するよう修正しました)

```sql
create table public.sounds (
  user_id uuid REFERENCES auth.users (id) DEFAULT auth.uid() NOT NULL,
  icon text,
  title text,
  ...

  primary key (id)
);

alter table public.sounds enable row level security;
```

[参考記事](https://qiita.com/kabochapo/items/26b1bb753116a6904664#%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E4%BD%9C%E6%88%90-1)

**Comment by mono-nobe** [comment]
設計完了したためcloseする。
