### ISSUE TITLE
リソース(URL)設計する

### ISSUE THREAD

**Issue by mono-nobe** [mono-nobe/sounds-album#40]
# Goal

リソース設計が以下のような形式でまとめられている

Method | Path | Description
-- | -- | --
GET | /foo | fooの一覧を表示。
POST | /foo | fooを受け取って追加する。
DELETE | /foo/123 | fooのidを受け取って削除する。
GET | /bar | barの一覧を表示。

## 使用技術

- https://github.com/mono-nobe/sounds-album/issues/27
- https://github.com/mono-nobe/sounds-album/issues/28
- https://github.com/mono-nobe/sounds-album/issues/29
- https://github.com/mono-nobe/sounds-album/issues/31
- https://github.com/mono-nobe/sounds-album/issues/32

**Comment by mono-nobe** [comment]
想定されるリソース設計を以下に記載する。

Method | Path | Description
-- | -- | --
GET | / | トップ画面。ログイン前はウェルカム画面、ログイン後はサウンド一覧画面へ遷移する
GET | /welcome | ウェルカム画面を表示する
GET | /tos | 利用規約画面を表示する
GET | /pp | プライバシーポリシー画面を表示する
GET | /sign-up | サインアップ画面を表示する
POST | /sign-up | サインアップを実行する
GET | /sign-in | サインイン画面を表示する
POST | /sign-in | サインインを実行する
POST | /sign-out | サインアウトを実行する
GET | /reset-password | パスワードリセット(忘れた時の)画面を表示する
POST | /reset-password | パスワードリセット対象のメールアドレスを送信する
GET | /new-password | 新しいパスワードを入力する画面を表示する
PUT | /new-password | 新しいパスワードに更新する
GET | /profile | アカウント情報を取得しアカウント編集画面を表示する
PUT | /profile | アカウント情報を受け取って更新する
GET | /sounds | サウンド一覧を取得してサウンド一覧画面を表示する
GET | /sounds/new | サウンド情報作成する画面を表示する
POST | /sounds | サウンド情報を受け取って作成する
GET | /sounds/{sound-id} | サウンド情報を取得しサウンド詳細画面を表示する
GET | /sounds/{sound-id}/edit | サウンド情報を取得しサウンド編集画面を表示する
PUT | /sounds/{sound-id} | サウンド情報を受け取って更新する
DELETE | /sounds/{sound-id} | サウンド情報を受け取って削除する

**Comment by maedana** [comment]
- プライバシーポリシーを`/pp`にするのって一般的なんですかね? 利用規約を/tosとするのはは見たことありますが。
- Rails前提とするなら`/sign-up`のようなURLはスネークケースになるかなと思います。今全体的にケバブケースっぽいですね。
- 明記するまでもないってことかもですが、パスワード忘れが抜けてますね。サインアップ/サインインなどひっくるめてもしdevise前提なら省略してもいいぐらいですが。
- `/account`ですが、DBと同じ命名でいいんじゃないですかね。あえて変えたい理由があるんでしょうか
- サウンド作成画面、サウンド作成はRails前提のRESTなURIとしてはちょっと変かなと思います。

**Comment by mono-nobe** [comment]
@maedana 
レビューありがとうございます！

> プライバシーポリシーを/ppにするのって一般的なんですかね? 利用規約を/tosとするのはは見たことありますが。

`/pp` については、フィヨルドのプライバシーポリシーを参考にしました 👀 

> Rails前提とするなら/sign-upのようなURLはスネークケースになるかなと思います。今全体的にケバブケースっぽいですね。

使用技術に関する情報が漏れていたため、概要に追記しました 🙇 
今回はRailsを使用せず、Next.js での実装を考えております。

> 明記するまでもないってことかもですが、パスワード忘れが抜けてますね。サインアップ/サインインなどひっくるめてもしdevise前提なら省略してもいいぐらいですが。

ご指摘ありがとうございます！
完全に抜け落ちていたので追記しました...

> /accountですが、DBと同じ命名でいいんじゃないですかね。あえて変えたい理由があるんでしょうか

DBとの関連性を意識できておりませんでした。
`/profile(DBでの命名)` の方がしっくりくるのでそちらに寄せる形にします！

> サウンド作成画面、サウンド作成はRails前提のRESTなURIとしてはちょっと変かなと思います。

Next.js(バックエンドの機能も統合する)を用いる想定です。
とはいえ、フロントエンドのルーティングまで含めてしまったため不自然なURIとなってしまいました。。
前提の話となり恐縮ですが、一般的にリソース設計を記載する際はフロントエンド側のルーティングのURL(今回では利用規約やプライバシーポリシーの表示など)は含めない方が良いのでしょうか？ 👀 
(フロントエンドとバックエンドを分けて書くのが良いですかね？)

**Comment by maedana** [comment]
> /pp については、フィヨルドのプライバシーポリシーを参考にしました 👀

なるほどー、OKです。

> 使用技術に関する情報が漏れていたため、概要に追記しました 🙇
今回はRailsを使用せず、Next.js での実装を考えております。

先に確認すればよかったですね。OKです

> ご指摘ありがとうございます！
完全に抜け落ちていたので追記しました...

:+1: 

> DBとの関連性を意識できておりませんでした。
/profile(DBでの命名) の方がしっくりくるのでそちらに寄せる形にします！

:+1: 

> Next.js(バックエンドの機能も統合する)を用いる想定です。
とはいえ、フロントエンドのルーティングまで含めてしまったため不自然なURIとなってしまいました。。
前提の話となり恐縮ですが、一般的にリソース設計を記載する際はフロントエンド側のルーティングのURL(今回では利用規約やプライバシーポリシーの表示など)は含めない方が良いのでしょうか？ 👀
(フロントエンドとバックエンドを分けて書くのが良いですかね？)

フロントエンド/バックエンドとかはあまり関係なくて、HTTPのリクエストとして分かれるものは全部明記したらいいかと思います。
https://bootcamp.fjord.jp/products/16710#-11
を拝見すると専用画面がありますし、`/sounds/new`みたいな専用URLで開くのかと思ってましたけど、そうではなくSPA的にクライアント側だけで画面切り替えるってことですか? だとしても保存は`POST /sound`と単数系でなく、複数形が適切ではないかなと思いました。

**Comment by mono-nobe** [comment]
@maedana 
> フロントエンド/バックエンドとかはあまり関係なくて、HTTPのリクエストとして分かれるものは全部明記したらいいかと思います。

承知しました！ありがとうございます。

> 拝見すると専用画面がありますし、/sounds/newみたいな専用URLで開くのかと思ってましたけど、そうではなくSPA的にクライアント側だけで画面切り替えるってことですか? 

専用URLで開く想定です。
`/sounds/new` とした方が適切なので修正しました！ 

> だとしても保存はPOST /soundと単数系でなく、複数形が適切ではないかなと思いました。

複数形に修正しました。
複数形が適切な理由については以下の記事を参考に納得したのですが、もし他にも理由があれば教えていただきたいです 🙇

[エンドポイントの名前が複数形であるべき理由
](https://qiita.com/ryo88c/items/0a3c7861015861026e00#%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%81%AE%E5%90%8D%E5%89%8D%E3%81%8C%E8%A4%87%E6%95%B0%E5%BD%A2%E3%81%A7%E3%81%82%E3%82%8B%E3%81%B9%E3%81%8D%E7%90%86%E7%94%B1)

**Comment by maedana** [comment]
> [エンドポイントの名前が複数形であるべき理由](https://qiita.com/ryo88c/items/0a3c7861015861026e00#%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%81%AE%E5%90%8D%E5%89%8D%E3%81%8C%E8%A4%87%E6%95%B0%E5%BD%A2%E3%81%A7%E3%81%82%E3%82%8B%E3%81%B9%E3%81%8D%E7%90%86%E7%94%B1)

参考文献は拝見したことなかったですが、納得出来る理由です。一方で明確に単数しか存在しないものなら僕ならエンドポイントは単数形にしますねー。

**Comment by maedana** [comment]
前回のバージョンが残ってないので指摘漏れかどうか判断がつかないですが、

> パスワードリセット(忘れた時の)画面を表示する
> パスワードリセットを実行する

については細かいことをいうと`パスワードを忘れ方はこちら`をクリックで`リセットURL発行画面`でこの画面で`リセットURL発行`すると、`リセット画面`で、ここでやっと`リセット実行`と4つのURIがあるんじゃないかなぁと。Railsのdevise gemだとそれらが
GET /users/password/new
POST /users/password
GET /users/password/edit?reset_password_token=xxxx
PUT /users/password
のように割り当てられてたりしますねー。なので2つ足りないのかなと。いかがでしょうか。でもこの辺は[Supabase](https://supabase.com/) に乗っかるだろうしあまり考えなくていいのかも?

**Comment by mono-nobe** [comment]
@maedana 
> 一方で明確に単数しか存在しないものなら僕ならエンドポイントは単数形にしますねー。

時と場合によっては単数形にする形でも問題ないと理解しました！
今回の `sounds` は複数存在するものになるため、いただいたように複数形が適切そうです 👀 

> なので2つ足りないのかなと。いかがでしょうか。でもこの辺は[Supabase](https://supabase.com/) に乗っかるだろうしあまり考えなくていいのかも?

確認したところ、エンドポイントが足りていないので追加しました！
また、Supabaseにおけるパスワードリセットは以下のような手順になりそうです。

1. `パスワードを忘れた方はこちら`をクリックする
    1. => パスワード更新メールを送信するためのメールアドレスを入力するページへ遷移する
1. メールアドレスを入力して送信ボタンをクリックする
    1. => Supabaseからパスワード更新画面へのリンク付きメールが送信される
1. メールのリンクをクリックする
    1. => パスワード更新画面へ遷移する
1. 新しいパスワードを入力して送信ボタンをクリックする
    1. => パスワードが更新される
    1. また、事前に設定しておいたリダイレクト先に遷移する

- [Supabase：Password Reset](https://supabase.com/docs/guides/auth/auth-password-reset)
- [Supabaseでのパスワードリセット](https://www.sukerou.com/2022/12/supabase_14.html)

**Comment by mono-nobe** [comment]
設計が完了したためcloseにする
